---
label: Project
hide_body: false
fields:
- name: layout
  type: select
  default: project-page
  config:
    required: true
    options:
    - project-page
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Layout
- name: title
  type: text
  config:
    required: false
  label: Title
- name: caption
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Caption
- name: background_color
  type: color
  label: Background Color
  config:
    required: false
    color_format: Hex
pages:
- pages/project/guidepanels.mdx
