---
label: Project
hide_body: false
fields:
- name: layout
  type: select
  default: project-page
  config:
    required: true
    options:
    - project-page
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Layout
- name: show_on_homepage
  type: boolean
  label: Show on homepage
- name: display_order
  type: number
  label: Display order
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: title
  type: text
  config:
    required: false
  label: Title
- name: caption
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Caption
- name: background_color
  type: color
  label: Background Color
  config:
    required: false
    color_format: Hex
- name: project_info
  type: field_group_list
  fields:
  - name: title
    type: text
    config:
      required: true
    label: Title
  - name: list_item
    type: list
    config:
      use_select: false
      min: 
      max: 
    label: List Item
  config:
    min: 
    max: 
    labelField: 
  label: Project Info
pages:
- pages/project/guidepanels.mdx
